[package]
name = "desktop_gremlin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bad-signals = "0.1.0"
fontdue = "0.9.3"
harfrust = "0.4.0"
image = "0.25.9"
rand = "0.9.2"
sdl3 = { version = "0.16.2", features = ["build-from-source"] }
